[build]
  command = "npm run build:client"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "20.5.1"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
