[build]
  # Usa o pnpm para instalação e build
  command = "pnpm install && pnpm run build"
  # Onde o build do cliente (frontend estático) é gerado
  publish = "dist/spa"
  # Onde o Netlify deve procurar suas funções serverless
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.5.1"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
